name: Deploy to Raspberry Pi

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: cd reactapp && npm install

      - name: Build project
        env:
          REACT_APP_API_KEY: ${{ secrets.REACT_API_KEY }}
        run: cd reactapp && npm run build

      
      - name: SSH connection
        env:
          SSH_KEY: ${{ secrets.PI_SSH_KEY }}
          PI_HOST: ${{ secrets.PI_HOST }}
          PI_USER: ${{ secrets.PI_USER }}
        run: |
          mkdir -p ~/.ssh
          echo "$SSH_KEY" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H "${{ secrets.PI_HOST }}" >> ~/.ssh/known_hosts
          ssh -vvv ${PI_USER}@${PI_HOST} "echo 'SSH connection successful'"

      - name: Copy files to Raspberry Pi
        env:
          REACT_APP_API_KEY: ${{ secrets.REACT_API_KEY }}
          SSH_KEY: ${{ secrets.PI_SSH_KEY }}
          PI_HOST: ${{ secrets.PI_HOST }}
          PI_USER: ${{ secrets.PI_USER }}
        run: |
          # Rsync the build folder
          rsync -avz --delete ./build/ ${PI_USER}@${PI_HOST}:~/pi/reactapp/build/

          # Rsync other folders (exclude .git and build if needed)
          rsync -avz --exclude build --exclude .git --exclude reactapp ./ ${PI_USER}@${PI_HOST}:~/pi
