name: Deploy to Raspberry Pi

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies for web app
        run: cd reactapp && npm install

      - name: Install dependecies for scraping
        run: cd scraping && npm install

      - name: Build project
        env:
          REACT_APP_API_KEY: ${{ secrets.REACT_API_KEY }}
          REACT_APP_BIN_DATE_URL: ${{ secrets.REACT_APP_BIN_DATE_URL }}
        run: cd reactapp && npm run build
      
      - name: Copy build to Raspberry Pi
        uses: appleboy/scp-action@v0.1.4
        with:
          host: ${{ secrets.PI_HOST }}
          username: ${{ secrets.PI_USER }}
          key: ${{ secrets.PI_SSH_KEY }}
          port: ${{ secrets.PI_SSH_PORT }}
          source: "reactapp/build/*"
          target: "~/pi/"

      - name: Copy epaper to Raspberry Pi
        uses: appleboy/scp-action@v0.1.4
        with:
          host: ${{ secrets.PI_HOST }}
          username: ${{ secrets.PI_USER }}
          key: ${{ secrets.PI_SSH_KEY }}
          port: ${{ secrets.PI_SSH_PORT }}
          source: "epaper/*"
          target: "~/pi/"

      - name: Copy scraping to Raspberry Pi
        uses: appleboy/scp-action@v0.1.4
        with:
          host: ${{ secrets.PI_HOST }}
          username: ${{ secrets.PI_USER }}
          key: ${{ secrets.PI_SSH_KEY }}
          source: "scraping/*"
          target: "~/pi/"

      - name: Deploy app or restart service on Pi
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.PI_HOST }}
          username: ${{ secrets.PI_USER }}
          key: ${{ secrets.PI_SSH_KEY }}
          script: |
            echo "Deploying on Raspberry Pi..."
            chmod +x ~/pi/epaper/update-screen.sh
            bash ~/pi/epaper/update-screen.sh
            echo "Deployment completed."